package com.capitalone.dynamodb.model;

import java.util.Date;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "exchange")
public class Exchange {

    
	private String id;
	private Long exchangeId;
	private String exchangeFrom;
	private String exchangeTo;
	private Float rate;
	private Date updatedDate;
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "id")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
//	@DynamoDBRangeKey(attributeName = "exchangeId")
	public Long getExchangeId() {
		return exchangeId;
	}

	public void setExchangeId(Long exchangeId) {
		this.exchangeId = exchangeId;
	}

	@DynamoDBAttribute
	public String getExchangeFrom() {
		return exchangeFrom;
	}

	public void setExchangeFrom(String exchangeFrom) {
		this.exchangeFrom = exchangeFrom;
	}

	@DynamoDBAttribute
	public String getExchangeTo() {
		return exchangeTo;
	}

	public void setExchangeTo(String exchangeTo) {
		this.exchangeTo = exchangeTo;
	}

	@DynamoDBAttribute
	public Float getRate() {
		return rate;
	}

	public void setRate(Float rate) {
		this.rate = rate;
	}

	@DynamoDBAttribute
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Override
	public String toString() {
		return "Exchange [id=" + id + ", exchangeId=" + exchangeId + ", exchangeFrom=" + exchangeFrom + ", exchangeTo="
				+ exchangeTo + ", rate=" + rate + ", updatedDate=" + updatedDate + "]";
	}

	
}
